### ISSUE TITLE
Add Next react app

### ISSUE THREAD

**Issue by manuelgeek** [manuelgeek/nx-vite-infra#2]
use https://nx.dev/nx-api/next/generators/application generators

**Comment by cliffgor** [comment]
@manuelgeek I want to pick up on this issue

**Comment by manuelgeek** [comment]
@cliffgor OK

**Comment by danielotieno** [comment]
@cliffgor, are you still working on this?

**Comment by cliffgor** [comment]
@danielotieno Yes i should push updates during the week
